#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export LANG=en_AU.UTF-8

. `brew --prefix`/etc/profile.d/z.sh

# Base16 Shell
#BASE16_SCHEME="solarized"
BASE16_SHELL="$HOME/.config/base16-shell/base16-atelierdune.light.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:$HOME/bin

export ANDROID_HOME=/usr/local/opt/android-sdk
export PATH=$PATH:/usr/local/opt/go/libexec/bin


# Make vim the default editor
export EDITOR="vim";

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help";

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";

export MANWIDTH=80
