#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export LANG=en_AU.UTF-8

. `brew --prefix`/etc/profile.d/z.sh

# Base16 Shell
#BASE16_SCHEME="solarized"
BASE16_SHELL="$HOME/.config/base16-shell/base16-atelierdune.light.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:$HOME/bin

export ANDROID_HOME=/usr/local/opt/android-sdk
export PATH=$PATH:/usr/local/opt/go/libexec/bin
